### ISSUE TITLE
Hi there. Search() is not working as expected. It is hanging up as I make a request. I believe the reason is kijiji updated their search functionality

### ISSUE THREAD

**Issue by mohaimenhasan** [mwpenny/kijiji-scraper#19] opened 2019-06-25 19:09 UTC
I am trying to use the NPM module to make a request. However, the request is hanging up.

**Comment by mwpenny** [comment] 2019-07-12 03:04
Hi there, I'm sorry I only saw this now. I was able to successfully use the search functionality as expected using the latest version.

Could you please provide example code that reproduces the problem? Thanks!

**Comment by mwpenny** [comment] 2019-08-09 12:36
Is this still a problem for you? I've been unable to reproduce it. I'd like to close this issue

**Comment by mwpenny** [comment] 2019-08-12 12:28
Cannot reproduce. Closing

**Closed as completed** 2019-08-12 12:29 UTC
Labels: not a bug
