### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jas124** [mwpenny/kijiji-scraper#71] opened 2023-12-18 13:33 UTC
Doesnt seem to be working. Has Kijiji changed something?

**Comment by tarps00** [comment] 2023-12-18 14:26
Same here, mingle.kijiji.ca is returning a 502 error since sunday at noon. Maybe the endpoint URL changed?

**Comment by mwpenny** [comment] 2023-12-18 16:04
Can you share sample code that reproduces the issue?

I was just able to both search and retrieve the details of a specific ad successfully using the mobile API (the default).

HTML-based searching (not the default) is broken, and I will fix that, but out-of-the box everything should work.

**Comment by tarps00** [comment] 2023-12-18 16:14
It started working again at around 9:30. I think it might be a problem on Kijiji's side. The android app v<18 wasn't working either and some people mentioned that they couldn't get message notification by email.

**Comment by jas124** [comment] 2023-12-18 16:21
Seems to me that Kijiji is experimenting with some kind of rate limiting and it does not appear to be IP based on the API. I believe it is based on the version of the app you are using. I have been running scrapers for years with no issues and using proxies for the requests. In the last couple weeks there has been many hours of downtime. Some versions of the mobile app continue to work while scrapers do not. This appears to be working again.

**Comment by mwpenny** [comment] 2023-12-18 17:20
Sounds like some brief downtime on Kijiji's side. I'll close this issue.

As for rate limiting, the scraper allows you to add delays between requests. See the `pageDelayMs` option in the readme. Feel free to open another issue if they are outright blocking the mechanism used by this library.

Also I've fixed the HTML searcher and pushed to NPM.

**Closed as completed** 2023-12-18 17:21 UTC
Labels: troubleshooting
